language: go

go:
  - 1.9

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - ginkgo -r --trace ./pkg
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false
